kind: Template
apiVersion: v1
metadata:
  name: python-test
  annotations:
    description: The Service template
    tags: python-test
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: python-test
    labels:
      app: python-test
  spec:
    ports:
    - name: python-test
      port: 9090
    selector:
      app: python-test